### ISSUE TITLE
lab_id in inputs name

### ISSUE THREAD

**Issue by andreaa93** [FAIRmat-NFDI/nomad-analysis#23]
would be convenient to write the lab_id in the name of the referenced archive so it is visualized in the list of inputs in the analysis entry

**Comment by ka-sarthak** [comment]
I agree it will be a nice addition. The `inputs` SectionReferences will try to use the lab-id or the name (in that order), if available, otherwise set it to default value.

**Comment by andreaa93** [comment]
klingt gut auch
