### ISSUE TITLE
Refer all entries belonging to a certain class

### ISSUE THREAD

**Issue by ka-sarthak** [FAIRmat-NFDI/nomad-analysis#8]
For large data analysis, like ML applications, one might want to add input references to large number of entries. Currently, to do this, they have to add each input reference individually. 

Make a quantity that asks for an entry class and collects all the available entries of that class. These entries are then attached to the input.

@aalbino2 Does this makes sense? Please add your suggestions or comments.

**Comment by andreaa93** [comment]
Would this be a new kind of quantity or just a string that you then process in some normalize function with some API query?

**Comment by ka-sarthak** [comment]
@aalbino2  I am thinking of just a string for now. But it will great if we can make a drop down selection (Enum) which gets updated based on what Entry classes are available to the user. I don't know if it's possible with current EditQuantities.

The implementation can be broadly divided into two parts: 
- selection of the EntryClass
- fetching of the entry_ids and attaching to the input sub-section

We can start with a StringEditQuantity for the first part and improve later. In the meantime, i will set up the API calls and also make a feature request for an appropriate selection Edit Quantity.

**Comment by andreaa93** [comment]
I see. The new quantity idea is not bad! Let's see if it can be designed in a general enough way to be worth the implementation

Thanks, in any case this issue targets my needs for the prototype ipynb file we were discussing.

Go ahead! 👍🏼
